### ISSUE TITLE
Redis

### ISSUE THREAD

**Issue by kazanjig** [kumy/Automatic-Chicken-Coop-Door-Opener#6]
Hi kumy,

In your instructions should it be 'redis-server' instead of 'redis'? I'm getting "E: Unable to locate package redis".

Thanks.

kazanjig

**Comment by kumy** [comment]
Odd, I do not have this error `Executable path is not absolute`

What is the distribution running on your raspberry?
```
# Mine
$ lsb_release  -a
No LSB modules are available.
Distributor ID:	Raspbian
Description:	Raspbian GNU/Linux 10 (buster)
Release:	10
Codename:	buster
```

https://github.com/kumy/Automatic-Chicken-Coop-Door-Opener/blob/f19d298ffe2f0fccbf147f80e7a2b5d1b8f3b568/other/chicken-coop.service#L14

You can try to replace `authbind` L14 by it's absolute path `/usr/bin/authbind` as requested. Don't forget to reload systemd daemon when making changes to this file (`sudo systemctl daemon-reload`)

**Comment by kazanjig** [comment]
I'm running Stretch 9.13. Let me try upgrading to Buster and see what
happens.

**Comment by kazanjig** [comment]
New errors now.

***@***.***:~ $ systemctl status chicken-coop.service
● chicken-coop.service - Automatic Chicken Coop Door Opener
   Loaded: loaded (/etc/systemd/system/chicken-coop.service; enabled;
vendor preset: enabled)
   Active: activating (auto-restart) (Result: exit-code) since Fri
2021-10-29 16:27:57 EDT; 4s ago
  Process: 3155 ExecStartPre=/bin/mkdir /run/chicken-coop (code=exited,
status=200/CHDIR)
  Process: 3156 ExecStopPost=/bin/rm -rf /run/chicken-coop (code=exited,
status=200/CHDIR)


***@***.***:~ $ journalctl -xe
-- The job identifier is 8485.
Oct 29 16:29:21 supercoop systemd[3273]: chicken-coop.service: Changing to
the requested working directory failed: No such
Oct 29 16:29:21 supercoop systemd[3273]: chicken-coop.service: Failed at
step CHDIR spawning /bin/mkdir: No such file or d
-- Subject: Process /bin/mkdir could not be executed
-- Defined-By: systemd
-- Support: https://www.debian.org/support
-- 
-- The process /bin/mkdir could not be executed and failed.
-- 
-- The error number returned by this process is ERRNO.
Oct 29 16:29:21 supercoop systemd[1]: chicken-coop.service: Control process
exited, code=exited, status=200/CHDIR
-- Subject: Unit process exited
-- Defined-By: systemd
-- Support: https://www.debian.org/support
-- 
-- An ExecStartPre= process belonging to unit chicken-coop.service has
exited.
-- 
-- The process' exit code is 'exited' and its exit status is 200.
Oct 29 16:29:21 supercoop systemd[3274]: chicken-coop.service: Changing to
the requested working directory failed: No such
Oct 29 16:29:21 supercoop systemd[3274]: chicken-coop.service: Failed at
step CHDIR spawning /bin/rm: No such file or dire
-- Subject: Process /bin/rm could not be executed
-- Defined-By: systemd
-- Support: https://www.debian.org/support
-- 
-- The process /bin/rm could not be executed and failed.
-- 
-- The error number returned by this process is ERRNO.
Oct 29 16:29:21 supercoop systemd[1]: chicken-coop.service: Control process
exited, code=exited, status=200/CHDIR
-- Subject: Unit process exited
-- Defined-By: systemd
-- Support: https://www.debian.org/support
-- 
-- An ExecStopPost= process belonging to unit chicken-coop.service has
exited.
-- 
-- The process' exit code is 'exited' and its exit status is 200.
Oct 29 16:29:21 supercoop systemd[1]: chicken-coop.service: Failed with
result 'exit-code'.
-- Subject: Unit failed
-- Defined-By: systemd
-- Support: https://www.debian.org/support
-- 
-- The unit chicken-coop.service has entered the 'failed' state with result
'exit-code'.
Oct 29 16:29:21 supercoop systemd[1]: Failed to start Automatic Chicken
Coop Door Opener.
-- Subject: A start job for unit chicken-coop.service has failed
-- Defined-By: systemd
-- Support: https://www.debian.org/support
-- 
-- A start job for unit chicken-coop.service has finished with a failure.
-- 
-- The job identifier is 8485 and the job result is failed.
lines 5693-5741/5741 (END)
-- The job identifier is 8485.
Oct 29 16:29:21 supercoop systemd[3273]: chicken-coop.service: Changing to
the requested working directory failed: No such file or directory
Oct 29 16:29:21 supercoop systemd[3273]: chicken-coop.service: Failed at
step CHDIR spawning /bin/mkdir: No such file or directory
-- Subject: Process /bin/mkdir could not be executed
-- Defined-By: systemd
-- Support: https://www.debian.org/support
-- 
-- The process /bin/mkdir could not be executed and failed.
-- 
-- The error number returned by this process is ERRNO.
Oct 29 16:29:21 supercoop systemd[1]: chicken-coop.service: Control process
exited, code=exited, status=200/CHDIR
-- Subject: Unit process exited
-- Defined-By: systemd
-- Support: https://www.debian.org/support
-- 
-- An ExecStartPre= process belonging to unit chicken-coop.service has
exited.
-- 
-- The process' exit code is 'exited' and its exit status is 200.
Oct 29 16:29:21 supercoop systemd[3274]: chicken-coop.service: Changing to
the requested working directory failed: No such file or directory
Oct 29 16:29:21 supercoop systemd[3274]: chicken-coop.service: Failed at
step CHDIR spawning /bin/rm: No such file or directory
-- Subject: Process /bin/rm could not be executed
-- Defined-By: systemd
-- Support: https://www.debian.org/support
-- 
-- The process /bin/rm could not be executed and failed.
-- 
-- The error number returned by this process is ERRNO.
Oct 29 16:29:21 supercoop systemd[1]: chicken-coop.service: Control process
exited, code=exited, status=200/CHDIR
-- Subject: Unit process exited
-- Defined-By: systemd
-- Support: https://www.debian.org/support
-- 
-- An ExecStopPost= process belonging to unit chicken-coop.service has
exited.
-- 
-- The process' exit code is 'exited' and its exit status is 200.
Oct 29 16:29:21 supercoop systemd[1]: chicken-coop.service: Failed with
result 'exit-code'.
-- Subject: Unit failed
-- Defined-By: systemd
-- Support: https://www.debian.org/support
-- 
-- The unit chicken-coop.service has entered the 'failed' state with result
'exit-code'.
Oct 29 16:29:21 supercoop systemd[1]: Failed to start Automatic Chicken
Coop Door Opener.
-- Subject: A start job for unit chicken-coop.service has failed
-- Defined-By: systemd
-- Support: https://www.debian.org/support
-- 
-- A start job for unit chicken-coop.service has finished with a failure.
-- 
-- The job identifier is 8485 and the job result is failed.
lines 5693-5741/5741 (END)

**Comment by kumy** [comment]
`spawning /bin/mkdir: No such file or directory`
`spawning /bin/rm: No such file or directory`

`mkdir` and `rm`, seems to not be present in the same path on your system. On mine i find them those path, just adapt path in your service file according to your system…

```
$ ls -l /bin/mkdir 
-rwxr-xr-x 1 root root 63400 Feb 28  2019 /bin/mkdir

$ ls -l /usr/bin/mkdir
-rwxr-xr-x 1 root root 63400 Feb 28  2019 /usr/bin/mkdir

$ ls -l /bin/rm /usr/bin/rm
-rwxr-xr-x 1 root root 51012 Feb 28  2019 /bin/rm
-rwxr-xr-x 1 root root 51012 Feb 28  2019 /usr/bin/rm

```
